name: Close Release Branch
on:
  workflow_dispatch:
    branches:
      - "releases/**"
jobs:
  CloseReleaseBranch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Initialize Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git fetch --prune --unshallow
      - name: Determine Next Version Name
        env:
          CURRENT_BRANCH: ${{ github.ref_name }}
        run: |
          NEXT_VERSION=`echo $CURRENT_BRANCH | tr -d release/ | tr -d hotfix/`
          echo "next_version=$NEXT_VERSION" >> $GITHUB_ENV
      - name: Merge Production And Main Branch
        env:
          CURRENT_BRANCH: ${{ github.ref_name }}
          NEXT_VERSION: ${{ env.next_version }}
        run: |
          TODAY=`date '+%Y/%m/%d'`
          CURRENT_BRANCH=${{ github.ref_name }}
          git tag -a $NEXT_VERSION -m "close $CURRENT_BRANCH with tag:$NEXT_VERSION at $TODAY"

          # production branch
          git checkout origin/production
          git merge $CURRENT_BRANCH --no-ff --no-edit
          git push origin/production

          # main branch
          git checkout origin/main
          git merge $CURRENT_BRANCH --no-ff --no-edit
          git push origin/main
      - name: Change Version Name And Commit
        env:
          CURRENT_BRANCH: ${{ github.ref_name }}
        run: |
          git push --delete origin $CURRENT_BRANCH --quiet
