name: Close Release Branch
on: workflow_dispatch
jobs:
  CloseReleaseBranch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Initialize Git
        run: |
          echo '1' $GITHUB_REF
          echo '2' ${{ github.ref }}
          echo '3' ${{ github.ref_name }}
          echo '4' ${{ github.head_ref }}
          echo '5' ${{ github.base_ref }}
      # - name: Determine Next Version Name
      #   run: |
      #     CURRENT_BRANCH=${{github.head_ref}}
      #     NEXT_VERSION=`echo $CURRENT_BRANCH | tr -d release/ | tr -d hotfix/`
      #     echo "next_version=$NEXT_VERSION" >> $GITHUB_ENV
      # - name: Change Version Name And Commit
      #   env:
      #     NEXT_VERSION: ${{ env.next_version }}
      #   run: |
      #     TODAY=`date '+%Y/%m/%d'`
      #     CURRENT_BRANCH=${{github.head_ref}}
      #     NEXT_VERSION= ${{ env.next_version }}
      #     git tag -a $NEXT_VERSION -m "close $CURRENT_BRANCH with tag:$NEXT_VERSION at $TODAY"

      #     # production branch
      #     git checkout origin/production
      #     git merge $CURRENT_BRANCH --no-ff --no-edit
      #     git push origin/production

      #     # main branch
      #     git checkout origin/main
      #     git merge $CURRENT_BRANCH --no-ff --no-edit
      #     git push origin/main
