name: Create Release Branch
on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      VersionUpType:
        description: "Version Up Type"
        default: Minor
        type: choice
        required: true
        options:
          - Major
          - Minor
          - Patch
jobs:
  CreateRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Initialize Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch --prune --unshallow
      - name: Determine Next Version Name
        run: |
          CURRENT_VERSION=`git describe --tags --abbrev=0`
          VERSION_UP_TYPE=${{ github.event.inputs.VersionUpType }}
          VERSION_ELEMENTS=( ${CURRENT_VERSION//[.|-]/ } )

          if [ $VERSION_UP_TYPE = "Major" ]; then
            NEXT_VERSION=$((VERSION_ELEMENTS[0]+1)).0.0
          elif [ $VERSION_UP_TYPE = "Minor" ]; then
            NEXT_VERSION=$((VERSION_ELEMENTS[0])).$((VERSION_ELEMENTS[1]+1)).0
          elif [ $VERSION_UP_TYPE = "Patch" ]; then
            NEXT_VERSION=$((VERSION_ELEMENTS[0])).$((VERSION_ELEMENTS[1])).$((VERSION_ELEMENTS[2]+1))
          fi

          echo "Current version is $CURRENT_VERSION"
          echo "Next version is $NEXT_VERSION"
