name: Create Release Branch
on: workflow_dispatch
jobs:
  CloseReleaseBranch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Initialize Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git fetch --prune --unshallow
      - name: Determine Next Version Name
        run: |
          CURRENT_BRANCH=`git symbolic-ref --short HEAD`
          NEXT_VERSION=`echo $CURRENT_BRANCH | tr -d release/ | tr -d hotfix/`
      - name: Change Version Name And Commit
        run: |
          TODAY=`date '+%Y/%m/%d'`
          git tag -a $NEXT_VERSION -m "close $CURRENT_BRANCH with tag:$NEXT_VERSION at $TODAY"

          # production branch
          git checkout origin/production
          git merge $CURRENT_BRANCH --no-ff --no-edit
          git push origin/production

          # main branch
          git checkout origin/main
          git merge $CURRENT_BRANCH --no-ff --no-edit
          git push origin/main
