name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      VersionUpType:
        description: "Version Up Type"
        default: Minor
        type: choice
        required: true
        options:
          - Major
          - Minor
          - Patch

jobs:
  createrelease:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Increment Version Tag
          run: |
           echo Hello