name: Create Release Branch
on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      VersionUpType:
        description: "Version Up Type"
        default: Minor
        type: choice
        required: true
        options:
          - Major
          - Minor
          - Patch
jobs:
  CreateRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Initialize Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch --prune --unshallow
      - name: Determine Next Version Name
        run: |
          CURRENT_VERSION=`git describe --tags --abbrev=0`
          echo $CURRENT_VERSION
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
