name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      VersionUpType:
        description: "Version Up Type"
        default: Minor
        type: choice
        required: true
        options:
          - Major
          - Minor
          - Patch

jobs:
  createrelease:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Create release branch
        run: git checkout -b release/v${{ github.event.inputs.versionName }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
