name: Select Environment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        type: environment
        required: true
jobs:
  ShowEnv:
    runs-on: ubuntu-latest
    steps:
      - name: Show Env
        run: |
          echo CI=$CI
          echo GITHUB_ACTION=$GITHUB_ACTION
          echo GITHUB_ACTION_PATH=$GITHUB_ACTION_PATH
          echo GITHUB_ACTION_REPOSITORY=$GITHUB_ACTION_REPOSITORY
          echo GITHUB_ACTIONS=$GITHUB_ACTIONS
          echo GITHUB_ACTOR=$GITHUB_ACTOR
          echo GITHUB_API_URL=$GITHUB_API_URL
          echo GITHUB_BASE_REF=$GITHUB_BASE_REF
          echo GITHUB_ENV=$GITHUB_ENV
          echo GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME
          echo GITHUB_EVENT_PATH=$GITHUB_EVENT_PATH
          echo GITHUB_GRAPHQL_URL=$GITHUB_GRAPHQL_URL
          echo GITHUB_HEAD_REF=$GITHUB_HEAD_REF
          echo GITHUB_JOB=$GITHUB_JOB
          echo GITHUB_PATH=$GITHUB_PATH
          echo GITHUB_REF=$GITHUB_REF
          echo GITHUB_REF_NAME=$GITHUB_REF_NAME
          echo GITHUB_REPOSITORY=$GITHUB_REPOSITORY
          echo GITHUB_STEP_SUMMARY=$GITHUB_STEP_SUMMARY
          echo GITHUB_WORKFLOW=$GITHUB_WORKFLOW
          echo RUNNER_ARCH=$RUNNER_ARCH
          echo RUNNER_NAME=$RUNNER_NAME
          echo RUNNER_TOOL_CACHE=$RUNNER_TOOL_CACHE
          echo ENV_TEST=$ENV_TEST
